#!/bin/fish

set touchpad "ASUP1205:00 093A:2003 Touchpad"

set touchpad_status (xinput list-props $touchpad | grep "Device Enabled" | awk '{print $NF}')
touch /tmp/touchpad_id
if test $touchpad_status -eq 1
    echo "Disabling touchpad..."
#		notify-send -p -r (cat /tmp/touchpad_id) -u normal -a touchpad "Disabling touchpad..." >> /tmp/touchpad_id
    xinput --disable $touchpad
else
    echo "Enabling touchpad..."
#		notify-send -p -r (cat /tmp/touchpad_id) -u normal -a touchpad "Enabling touchpad..." >> /tmp/touchpad_id
    xinput --enable $touchpad
end

